### ISSUE TITLE
Select Project Topic

### ISSUE THREAD

**Issue by Wayu650610806** [Wayu650610806/Curriculum#1]

**Comment by Wayu650610806** [comment]
wheel

**Comment by GOLF2546** [comment]
clock

**Comment by Wayu650610806** [comment]
schedule manage

**Comment by Wayu650610806** [comment]
จัดตารางเรียน ปี1-4 คณะวิศวะคอม

**Comment by Wayu650610806** [comment]
bmi calculator

**Comment by GOLF2546** [comment]
โปรแกรม บอกวิชาเรียนของเราปี 1 เทอม 1 เกณฑ์คะแนน ความยากง่ายจากการรีวิว

**Comment by Wayu650610806** [comment]
เกมต่อคำภาษาอังกฤษ

**Comment by Waphyoo** [comment]
เกมง่ายๆ ขาวดำในโทรสัพเมื่อก่อน เช่น เกมงู เกมขี่ยานยิงเอเลี่ยน

**Comment by Waphyoo** [comment]
![Screenshot_2023-02-10-21-43-42-277_com android chrome](https://user-images.githubusercontent.com/110945410/218120137-0879e831-0e9e-4f67-8fea-cf444e5b4fc1.jpg)
![Uploading Screenshot_2023-02-10-21-43-39-620_com.android.chrome.jpg…]()

**Comment by KnackPR** [comment]
Current Coverter แปลงค่าเงิน

**Comment by KnackPR** [comment]
Sudoku ?

**Comment by Wayu650610806** [comment]
![image](https://user-images.githubusercontent.com/110961218/218743958-511c6b41-4720-43cf-aa4f-6c9590ff43c2.png)
