### ISSUE TITLE
ref นน

### ISSUE THREAD

**Issue by Wayu650610806** [Wayu650610806/Curriculum#3]
สร้าง array 1 มิติ ของรหัสและรายชื่อวิชาภาษาอังกฤษ (2array) สำหรับ หัวข้อ Learner Person และ Innovative Co-creator 
*ตั้งชื่อให้ทุกคนเข้าใจ เรียงลำดับรหัสและวิชาให้ตรงกัน ห้ามผิดลำดับเด็ดขาด!!*
//ภาพประกอบ แคปมาไม่หมด หาเอาเอง//
//นนอย่าลิมเอาทั้งตัวบังคับ และตัวเลือกนะ มันอยู๋คนละที่กัน ถ้าดูน้อยแปลกๆแปลว่าไม่ครบละ//
![image](https://user-images.githubusercontent.com/110961218/218746946-92943d18-ec88-427e-9905-18744d596510.png)
![image](https://user-images.githubusercontent.com/110961218/218747001-5b6b3ccb-2510-4bb7-92b7-ed36fda94408.png)
![image](https://user-images.githubusercontent.com/110961218/218747076-20c7a0ed-d34c-4d3e-b062-a40acec88005.png)
![image](https://user-images.githubusercontent.com/110961218/218747295-814a539e-0e5d-4b98-a13c-6ee09012ab25.png)

**Comment by Waphyoo** [comment]
okok

**Comment by Waphyoo** [comment]
int key[]={001101,001102,001201,001225,204100,261111,953111,259192,013110,050106,176100,201114,201117,201190,207109,207110,368100,602201,610111,703103,751100,851103,852100};


string Eng1="Fundamental English 1";
string Eng2="Fundamental English 2";
string ReadWrite="Critical Reading and Effective Writing";
string Engsci="English in Science and Technology Context";
string Infotech="Information Technology and Modern Life";
string Internet="Internet and Online Community";
string Software="Software for Everyday Life";
string Skillpro="Skills for Professionalism and Entrepreneurship";
string Psychology="Psychology and Daily Life";
string Humanis="Humanistic Arts";
string Law="Humanistic Arts";
string Environment="Environmental Science in Today’s World";
string Math_Sci_Civil="	Mathematics and Science in Civilization";
string Thinking="Critical Thinking, Problem Solving and Science Communication";
string Life="Life and the Universe";
string Phy_Changed_World="Physics : the Science that Changed the World";
string Agribusiness="Starting an Agribusiness in a Changing World";
string Vision_Indus="Agro-Industrial Vision";
string Package="Packaging for Marketing";
string Intro_Entrepreneu="Introduction to Entrepreneurship and Business";
string Eco="Economics for Everyday Life";
string Media_Life="Life and Society through Media";
string Film="Introduction to Film";


string subject[]={Eng1,Eng2,ReadWrite,Engsci,Infotech,Internet,Software,Skillpro,Psychology,Humanis,Law,Environment,Math_Sci_Civil,Thinking,Life,Phy_Changed_World,Agribusiness,Vision_Indus,Package,Intro_Entrepreneu,Eco,Media_Life,Film}

**Comment by Wayu650610806** [comment]
pushลงช่องcode!

**Comment by Wayu650610806** [comment]
finished
