### ISSUE TITLE
Bug Fix

### ISSUE THREAD

**Issue by KnackPR** [Wayu650610806/Curriculum#31]

**Comment by KnackPR** [comment]
![image](https://user-images.githubusercontent.com/56012158/222942877-81940b2a-dc79-4dc6-9337-7879ca41e6d0.png)

**Comment by Waphyoo** [comment]
![image](https://user-images.githubusercontent.com/110945410/222942935-98053b73-11fd-4a09-861d-faa81536f28d.png)

**Comment by Waphyoo** [comment]
![image](https://user-images.githubusercontent.com/110945410/222943208-0b712fdb-f8ad-4b9e-84f4-ae52a1a6ffd9.png)
