### ISSUE TITLE
ref กอฟ

### ISSUE THREAD

**Issue by Wayu650610806** [Wayu650610806/Curriculum#5]
สร้าง array 1 มิติ ของรหัสและรายชื่อวิชาภาษาอังกฤษ (2array) สำหรับ หัวข้อCore Courses
ตั้งชื่อให้ทุกคนเข้าใจ เรียงลำดับรหัสและวิชาให้ตรงกัน ห้ามผิดลำดับเด็ดขาด!!
//ภาพประกอบ แคปมาไม่หมด หาเอาเอง//
//ทำไมของกอฟน้อยจัง;-;//
![image](https://user-images.githubusercontent.com/110961218/218748233-f764e699-2d81-44e3-aa26-c8dc919392f3.png)

**Comment by GOLF2546** [comment]
int  key[] = {206161,206162,206261,207105,207106,207115,207116,252281,259104,259106,261208,261216,261306};
    string Cal1 = "Calculus for Engineering 1";
    string Cal2 = "Calculus for Engineering 2";
    string Cal3 = "Calculus for Engineering 3";
    string Phy1 = "Physics for Engineering and Agro-Industry Students 1";
    string Phy2 = "Physics for Engineering and Agro-Industry Students 2";
    string PhyL1 = "Physics Laboratory for Engineering and Agro-Industry Students 1";
    string PhyL2 = "Physics Laboratory for Engineering and Agro-Industry Students 2";
    string Circuit = "Fundamentals of Electronic Circuits for Information Systems and Network Engineering";
    string Draw1 = "Engineering Drawing";
    string Workshop = "Workshop Technology";
    string Numeric = "Numerical Computation for Engineers";
    string DisMath = "Discrete Mathematics for Computer Engineers";
    string ProbStat = "Computer Engineering Probability and Statistics";
    string subject[] = {Cal1,Cal2,Cal3,Phy1,Phy2,PhyL1,PhyL2,Circuit,Draw1,Workshop,Numeric,DisMath,ProbStat};

**Comment by Wayu650610806** [comment]
finished
