### ISSUE TITLE
ref ฟลุ๊ค

### ISSUE THREAD

**Issue by Wayu650610806** [Wayu650610806/Curriculum#6]
สร้าง array 1 มิติ ของรหัสและรายชื่อวิชาภาษาอังกฤษ (2array) สำหรับ หัวข้อ major
ตั้งชื่อให้ทุกคนเข้าใจ เรียงลำดับรหัสและวิชาให้ตรงกัน ห้ามผิดลำดับเด็ดขาด!!
//ภาพประกอบ แคปมาไม่หมด หาเอาเอง//
//เอาแค่ของnormal planนะ ไม่ต้องเอาCooperative Education Plan//
![image](https://user-images.githubusercontent.com/110961218/218748770-22aa8650-2f13-4ea0-8e99-82fd4fbe25f2.png)

**Comment by flxk-NIthipong** [comment]
string code[]={"261405","261431","261492","261102","261200","261217","261218","261361","261103","261207","261332","261335","261336","261342","261343","261210","261212","261214","261215","261304","261305"};
    string subject[]={"Advanced Computer Engineering Technology","Project Survey,Project","Computer Programming","Object-Oriented Programming","Data Structures for Computer Engineers","Algorithms for Computer Engineers","Software Engineering","Basic Computer Engineering","Basic Computer Engineering Laboratory","Data and Computer Communications","Computer Networks","Computer Networks Laboratory","Fundamentals of Database Systems","Database System Laboratory","Logic and Digital Circuits","Logic and Digital Circuits Laboratory","Microprocessor and Interfacing","Embedded System Laboratory","Computer Architecture","Operating Systems"};   //There are 21 subjects in total.

**Comment by flxk-NIthipong** [comment]
อันนี้เเดียวมาใส่อย่างอื่นเพิ่มอีก(0.0)

**Comment by flxk-NIthipong** [comment]
#include<iostream>
#include<string>
using namespace std;

int main(){
    //There are 21 subjects in total.
    
    // There are 3 subjects in Technology_for_Application
    string Technology_for_Application_key[] = {"261405","261491","261492"};
    string AdvancedComENGR = "Advanced Computer Engineering Technology";
    string ProjSurvey = "Project Survey";
    string Project = "Project";
    string Technology_for_Application_subject[] = {"AdvancedComENGR","ProjSurvey","Project"};
    
    //There are 5 subjects in Technology_and_Software_Methods
    string Technology_and_Software_Methods_key[] = {"261102","261200","261217","261218","261361"};
    string ComProgramming = "Computer Programming";
    string ObjectProgramming = "Object-Oriented Programming";
    string DataStructres = "Data Structures for Computer Engineers";
    string Algorithms = "Algorithms for Computer Engineers";
    string SoftwareENGR = "Software Engineering";
    string Technology_for_Application_subject[] = {"ComProgramming","ObjectProgramming","DataStructres","Algorithms","SoftwareENGR"};
    
    //There are 7 subjects in Basic_Structure_of_the_Systems
    string Basic_Structure_of_the_Systems_key[] = {"261103","261207","261332","261335","261336","261342","261343"};
    string BasicCom = "Basic Computer Engineering";
    string BasicComLab = "Basic Computer Engineering Laboratory";
    string DataCommu = "Data and Computer Communications";
    string ComNetworks = "Computer Networks";
    string ComNetworksLab = "Computer Networks Laboratory";
    string DatabaseSystems = "Fundamentals of Database Systems";
    string DatabaseSystemsLab = "Database System Laboratory";
    string Basic_Structure_of_the_Systems_subject[]={"BasicCom","BasicComLab","DataCommu","ComNetworks","ComNetworksLab","DatabaseSystems","DatabaseSystemsLab"};
    
    //There are 6 subjects in Hardware_and_Computer_Architecture
    string Hardware_and_Computer_Architecture_key[] = {"261210","261212","261214","261215","261304","261305"};
    string DigitalCircuits = "Logic and Digital Circuits";
    string DigitalCircuitsLab = "Logic and Digital Circuits Laboratory";
    string Microprocessor = "Microprocessor and Interfacing";
    string EmbeddedSystemLab = "Embedded System Laboratory";
    string ComArchitecture = "Computer Architecture";
    string OperatingSystems = "Operating Systems";
    string Hardware_and_Computer_Architecture_subject[] = {"DigitalCircuits","DigitalCircuitsLab","Microprocessor","EmbeddedSystemLab","ComArchitecture","OperatingSystems"};
    
}

**Comment by flxk-NIthipong** [comment]
เดียวต้องไปหาตัวย่อที่มันดีกว่านี้ /^_^\

**Comment by Wayu650610806** [comment]
finished
