### ISSUE TITLE
ref แน็ค

### ISSUE THREAD

**Issue by Wayu650610806** [Wayu650610806/Curriculum#7]
สร้าง array 1 มิติ ของรหัสและรายชื่อวิชาภาษาอังกฤษ (2array) สำหรับ หัวข้อ major electives
ตั้งชื่อให้ทุกคนเข้าใจ เรียงลำดับรหัสและวิชาให้ตรงกัน ห้ามผิดลำดับเด็ดขาด!!
//ภาพประกอบ แคปมาไม่หมด หาเอาเอง//
![image](https://user-images.githubusercontent.com/110961218/218749415-3c9383ec-fc91-4e88-ab95-8c45169da537.png)
![image](https://user-images.githubusercontent.com/110961218/218749455-b7d041b2-b27a-42c5-b63a-3b3f42bdecc0.png)

**Comment by KnackPR** [comment]
//โค้ดนี้เอาไว้สำหรับเช็คว่าพิมพ์ code ตรงกับ subjects ไหม เท่าที่นับมา subject มี 53 วิชา พิมพ์เขาไปแทน i //
#include <iostream>
using namespace std;

int main(){
    string s_code[] = {"261404", "261406", "261407", "261408", "261409", "261411", "261414", "261421", "261424", "261430", "261433", "261434", "261435", "261437", "261438", "261439", "261441", "261444", "261446", "261447", "261448", "261449", "261453", "261456", "261457", "261458", "261459", "261461", "261465", "261468", "261469", "261470", "261471", "261472", "261473", "261475", "261476", "261478", "261479", "261493", "261494", "261497", "261498", "261499", "269421", "269430", "269431", "269432", "269433", "269441", "269461", "269462", "261400"} ;
    string subjects[] = {"Advanced Computer Engineering Laboratory", "Basic Compiler Design", "Fundamentals of Computation for Computer Engineers", "Quantum Computation", "Functional Programming", "Parallel Processing and Distributed Systems", "Digital System Design", "Computer Hardware Design", "Remote Monitoring and Control Systems", "Wireless Networks", "Network Programming", "Computer Network Design and Management", "Broadband Communication Networks", "Fundamentals of Queueing Theory for Computer Engineers", "Fundamentals of Multiprotocol Label Switching", "Wireless Communications for Computer Engineering", "Internet of Things and Big Data", "Advanced Database Systems", "Information Systems", "Network and Information Security", "Data Mining for Computer Engineering", "Software Testing for Computer Engineering", "Digital Image Processing", "Introduction to Computational Intelligence for Computer Engineering", "Digital Image and Video Compression", "Machine Vision", "Deep Learning", "Visual and Interactive Programming", "Computer Graphics", "System Analysis and Design for Computer Engineering", "Software Project Management for Computer Engineering", "Signals and Systems", "Advanced Digital Signal Processing", "Robotics", "Computer - Aided Manufacturing", "Modeling and Optimization for Big Data Analytics", "Biomedical Instruments", "Principles of Control Systems", "Bioinformatics Programming", "Seminar", "Selected Topics in Computer Engineering", "Selected Topics in Computer Software", "Selected Topics in Computer Networks", "Selected Topics in Computational Intelligence", "Computer Network Traffic Analysis", "Wireless And Broadband Computer Networks", "Wireless Sensor Network", "Peer-to-Peer Systems", "Computer Network Routing Protocols", "Information Retrieval and Extraction", "Personal Software Process Improvement", "Introduction to Human-Computer Interaction", "Computer Engineering Training"} ;
    //No. of subjects = 53
    int i ;
    cout << "Enter number of subject : " ;
    cin >> i ;
    cout << s_code[i] << "\n" << subjects[i] ;
}

**Comment by KnackPR** [comment]
//อันนี้โค้ดแบบปกติ//
#include <iostream>
using namespace std;

int main(){
    string s_code[] = {"261404", "261406", "261407", "261408", "261409", "261411", "261414", "261421", "261424", "261430", "261433", "261434", "261435", "261437", "261438", "261439", "261441", "261444", "261446", "261447", "261448", "261449", "261453", "261456", "261457", "261458", "261459", "261461", "261465", "261468", "261469", "261470", "261471", "261472", "261473", "261475", "261476", "261478", "261479", "261493", "261494", "261497", "261498", "261499", "269421", "269430", "269431", "269432", "269433", "269441", "269461", "269462", "261400"} ;
    string subjects[] = {"Advanced Computer Engineering Laboratory", "Basic Compiler Design", "Fundamentals of Computation for Computer Engineers", "Quantum Computation", "Functional Programming", "Parallel Processing and Distributed Systems", "Digital System Design", "Computer Hardware Design", "Remote Monitoring and Control Systems", "Wireless Networks", "Network Programming", "Computer Network Design and Management", "Broadband Communication Networks", "Fundamentals of Queueing Theory for Computer Engineers", "Fundamentals of Multiprotocol Label Switching", "Wireless Communications for Computer Engineering", "Internet of Things and Big Data", "Advanced Database Systems", "Information Systems", "Network and Information Security", "Data Mining for Computer Engineering", "Software Testing for Computer Engineering", "Digital Image Processing", "Introduction to Computational Intelligence for Computer Engineering", "Digital Image and Video Compression", "Machine Vision", "Deep Learning", "Visual and Interactive Programming", "Computer Graphics", "System Analysis and Design for Computer Engineering", "Software Project Management for Computer Engineering", "Signals and Systems", "Advanced Digital Signal Processing", "Robotics", "Computer - Aided Manufacturing", "Modeling and Optimization for Big Data Analytics", "Biomedical Instruments", "Principles of Control Systems", "Bioinformatics Programming", "Seminar", "Selected Topics in Computer Engineering", "Selected Topics in Computer Software", "Selected Topics in Computer Networks", "Selected Topics in Computational Intelligence", "Computer Network Traffic Analysis", "Wireless And Broadband Computer Networks", "Wireless Sensor Network", "Peer-to-Peer Systems", "Computer Network Routing Protocols", "Information Retrieval and Extraction", "Personal Software Process Improvement", "Introduction to Human-Computer Interaction", "Computer Engineering Training"} ;
    //No. of subjects = 53
}

**Comment by KnackPR** [comment]
อันนี้ทำ cout code กับ subject เผื่อเอาไว้เช็คว่า มันตรงกันไหมนะ

**Comment by KnackPR** [comment]
![image](https://user-images.githubusercontent.com/56012158/219017531-a7e6c17a-debf-47d4-ac88-3411f7a6422b.png)

**Comment by Wayu650610806** [comment]
finished
